# Generated by Django 6.0.6 on 2026-08-19 13:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(choices=[(1, 'Std 1'), (2, 'Std 2'), (3, 'Std 3'), (4, 'Std 4'), (5, 'Std 5'), (6, 'Std 6'), (7, 'Std 7'), (8, 'Std 8'), (9, 'Std 9'), (10, 'Std 10'), (11, 'Std 11'), (12, 'Std 12')], unique=True, verbose_name='Standard (Std)')),
                ('dress_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='1 Dress Price (₹)')),
                ('extra_dress_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='1 Extra Dress Price (₹)')),
                ('dupatta_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='1 Dupatta Price (₹)')),
                ('extra_dupatta_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='1 Extra Dupatta Price (₹)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Standard Price',
                'verbose_name_plural': 'Standard Prices',
                'ordering': ['standard'],
            },
        ),
        migrations.CreateModel(
            name='StudentDressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('standard', models.IntegerField(choices=[(1, 'Std 1'), (2, 'Std 2'), (3, 'Std 3'), (4, 'Std 4'), (5, 'Std 5'), (6, 'Std 6'), (7, 'Std 7'), (8, 'Std 8'), (9, 'Std 9'), (10, 'Std 10'), (11, 'Std 11'), (12, 'Std 12')], default=1, verbose_name='Standard')),
                ('medium', models.CharField(choices=[('GUJARATI', 'Gujarati'), ('ENGLISH', 'English')], default='GUJARATI', max_length=20, verbose_name='Medium')),
                ('package_model', models.CharField(choices=[('1_DRESS', '1 Dress'), ('1_DRESS_1_DUPATTA', '1 Dress + 1 Dupatta'), ('1_DRESS_1_EXTRA_1_DUPATTA', '1 Dress + 1 Extra Dress + 1 Dupatta'), ('1_DRESS_1_EXTRA_1_DUPATTA_1_EXTRA', '1 Dress + 1 Extra Dress + 1 Dupatta + 1 Extra Dupatta'), ('CUSTOM', 'Custom Selection')], default='1_DRESS', max_length=50, verbose_name='Dress Model / Package')),
                ('has_dress', models.BooleanField(default=True, verbose_name='1 Dress')),
                ('has_extra_dress', models.BooleanField(default=False, verbose_name='1 Extra Dress')),
                ('has_dupatta', models.BooleanField(default=False, verbose_name='1 Dupatta')),
                ('has_extra_dupatta', models.BooleanField(default=False, verbose_name='1 Extra Dupatta')),
                ('dress_qty', models.PositiveIntegerField(default=1, verbose_name='Dress Quantity')),
                ('dupatta_qty', models.PositiveIntegerField(default=0, verbose_name='Dupatta Quantity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Measurements / Remarks')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Price (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Student Dress Entry',
                'verbose_name_plural': 'Student Dress Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
